default: &default
  adapter: postgresql
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: covid_data_development
production:
  <<: *default
  database: covid_data_production
  # username: covid_data
  # password: <%= ENV['COVID_DATA_DATABASE_PASSWORD'] %>
